### PR TITLE
Skip buttons when filling login/password

### PR DESCRIPTION
**Pull request by mgorny**
Some login forms have submits/buttons named 'login'. Avoid replacing the values (labels) of those buttons with the login.

Happens for example on https://www.njumobile.pl/logowanie

### CODE REVIEW

**Comment by dchest** [comment]
Maybe it's better to include the types we're looking for rather than exclude the ones we don't like? E.g. `text` and `email`?

**Comment by mgorny** [comment]
I don't mind either way. I choose opt-out model because HTML5 introduces a lot of new input types, and I didn't want the script to break again when more specific types are introduced.

**Comment by dchest** [comment]
That's fine, because if they introduce `type="also-send-all-the-info-to-government"`, we won't fill it :-)

**Comment by mgorny** [comment]
Updated.

**Comment by dchest** [comment]
Thank you! Merged and uploaded to Chrome Web Store.

**Comment by mgorny** [comment]
Thanks for the quick response. I have a few more improvement ideas, and I'll try to implement them when I find some free time.

**Comment by dchest** [comment]
Great, thanks.

**Pull request merged**
